### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Kmfernan5** [CreArts-Community/CreArts-Obsidian#2]
**Describe the bug**
Crooked home page

**To Reproduce**
Steps to reproduce the behaviour:

1. Don’t know what I did. Ive only had theme for 15 min. I turned off templates and templated and then turned them back on could that have broken it?

**Expected behaviour**
Nothing. 

**Screenshots**
https://share.getcloudapp.com/xQuEAyD0

**Operating System:**

- [ ] Linux
- [ x] Windows 11
- [ ] macOS

**Additional context**

Should the templates folders be different how about the settings for all the other community plugins?

https://share.getcloudapp.com/xQuEAyD0

**Comment by CorellanStoma** [comment]
Now normally this should not be a problem, have you tried restarting Obsidian?


Maybe the .obsidian folder is not loaded properly.


No idea how you managed to do that, but it seems like the plugin configs are not loading properly.

**Comment by Kmfernan5** [comment]
Each of the community plugins have quite a number of variables what are your settings for each one?

**Comment by CorellanStoma** [comment]
The settings for the plugins are stored in this repo, after downloading everything should load automatically.
Most people had no problems so far, try redownloading the repo and make sure you have the latest version of the Obsidian client.

Then it should work.

**Comment by Kmfernan5** [comment]
I think it may bc I store my repos in Google Drive and didn’t sync offline before using.

**Comment by Kmfernan5** [comment]
DO you know why it looks like this? 

https://share.getcloudapp.com/RBuJkZeB

**Comment by CorellanStoma** [comment]
> 

hmm not really, maybe the metadata is not loaded correctly, did enabled the Plugins?
